# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
source:           src
title:            Jekyll Maps
tagline:          'A Jekyll plugin to easily embed maps with filterable locations.'
description:      'Easily embed GoogleMaps with locations from your Jekyll posts or data files.'
url:              https://ayastreb.github.io/jekyll-maps
baseurl:          /

author:
  name:           'Anatoliy Yastreb'
  url:            https://twitter.com/mrHabicht

github:
  repo:           https://github.com/ayastreb/jekyll-maps

gems:
  - jekyll-maps
  - redcarpet
  - pygments.rb
