# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
source:           src
title:            Jekyll Maps
tagline:          'A Jekyll plugin to easily embed maps with filterable locations.'
description:      'Easily embed GoogleMaps with locations from your Jekyll posts or data files.'
keywords:
  - jekyll plugin
  - jekyll maps
  - travel map
  - contacts map
  - embed google map
  - show map in jekyll
  - display map in blog
url:              https://ayastreb.me/jekyll-maps/
baseurl:          /jekyll-maps/

author:
  name:           'Anatoliy Yastreb'
  url:            https://twitter.com/mrHabicht

github:
  repo:           https://github.com/ayastreb/jekyll-maps

maps:
  google:
    api_key:      'AIzaSyDiswWoiEpfb14st7-VcFPtzLimC5Bhr4k'

plugins:
  - jekyll-maps
  - redcarpet
  - pygments.rb
